### ISSUE TITLE
lib is causing an ANR when it tries to remove the view from its parent not on the UI thread

### ISSUE THREAD

**Issue by yashareli** [kostasdrakonakis/tooltip_action#8]
TooltipActionView.removeNow() should be run on the UI thread. 
possible fix would be: 

rivate void removeNow() {
        post(new Runnable() {
            @Override
            public void run() {
                if (getParent() != null) {
                    final ViewGroup parent = ((ViewGroup) getParent());
                    parent.removeView(TooltipActionView.this);
                }
            }
        });
    }

**Comment by kostasdrakonakis** [comment]
Please try version 1.4.2 . The issue has been fixed. Thanks for the heads up 👍
